{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
  - host: {{ trimPrefix "https://" .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.config.ROOT_URL }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "ddns-updater.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls_enabled }}
  tls:
    - hosts:
        - {{ trimPrefix "https://" .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls_secretName }}
  {{- end }}
{{- end -}}