{{- if .Values.service.enable_app_service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ddns-updater.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.enable_hc_service -}}
apiVersion: v1
kind: Service
metadata:
  name: hc-{{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.health_check_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ddns-updater.selectorLabels" . | nindent 4 }}
{{- end }}